### ISSUE TITLE
Bank of China Hong Kong Account Opening Guide | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#21]
https://missuo.me/posts/bochk-open-account/ 

 本篇文章的部分信息来自于 推友@forecho的来香港办香港银行卡。感谢！
前往香港 这里我就简单说了，我这次的旅程有些复杂，HGH飞往ZUH。巴士到达拱北口岸，拱北口岸巴士到达深圳大学站。第二天从深圳湾口岸B3X前往屯门市中心（当然深圳湾口岸有巴士直接去市中心的，比如前往尖沙咀）。我是屯马线屯门站上车，美孚站换乘荃湾线到金钟站，再换乘港岛线到湾仔站。到达时间是4月14日周五下午三点左右，依次去了forecho推荐的湾仔分行和铜锣湾分行，都被告知今天名额满了。出门刚好看到附近还有HSBC HK，也进去问了一下，被告知如果没有预约的话无法办理，目前预约已经排到了五月份。
最后前往了我的好朋友Sark推荐的广东道分行，这个分行相对来说几乎是没什么客户的。前台的中年阿姨告知我，可以开卡，但是必须要存款100万港币。在我的来回拉扯下，我以朋友没存款100万港币开户成功，说她区别对待客户。最后到4点45分左右，她让我坐着等待让经理过来。但是因为我转运中国的货物在这个时候收到短信抵达了香港自提仓库，不得不直接离开广东道分行（自提仓库周末不开门，如果周五不取只能下周一），前往荃湾线的倒数第二站——大窝口。在下班前三分钟顺利取到了货物。
办卡当天 第二天周六，我八点就出发了，这一次学聪明了，去了一家相对来说比较偏僻的，不过周六所有的分行下午1点下班。大概是9点10分左右到达东铁线上水站，立马赶到上水银行服务中心（新界上水新丰路136号），排队的最后一个小姐姐告诉我她是最后一个开户的号码#30。此刻银行开门只有10分钟左右。请注意，附近的上水分行（新界上水新丰路61号）是不开户的。
于是，我就去了上水站另一头的上水中心分行（新界上水上水中心第一层1005-1009号），进去之后询问是否可以开户，得到了肯定的回答，我感到很惊喜。本来不抱希望了，还想着立马赶到广东道分行（该分行不太一样，是中银理财中心，简单说就是正常情况下只接待高端用户）去再和大堂的阿姨对线一下看看能不能给我开户。结果，这个上水中心分行比较烦的是，反复追问办卡需求，我说投资理财买保险。她会追问今天办好卡是否能立马存钱，能存多少万等等。如果当天存不了，需要你提供存款/余额证明等等。感觉最近某些分行因为每天大陆过去开户的客户太多，故意提高了这些门槛。
不过这些资产证明、收入证明之类的她是不用拍照留存、复印、扫描的，也不用上传系统的，只是柜员看一下而已。最后在我的瞎扯之下，她给我了一张#20的号。我以为应该很快就轮到我了，她让我一个小时后再来，我找了一家附近的麦当劳吃了个早饭，玩了会手机。大概10点半赶过去，她让我坐下来在BOCHK App填了一下开户基本信息。接着等着被叫号就行了。结果又等了两个多小时。而且这家分行只有一个座位，也就是意味着几乎所有人都是站着等。效率大概是一个号30-50分钟，非常慢。而且办理窗口只有一个。我前面有位#17的老哥，看样子也不会说粤语，应该也是来自内地非广东地区的。拿出了一个顺丰快递的文件信封来证明自己的住址。结果被柜员小姐姐狠狠地教育了一顿，说这个不是信件，这个是信封，无法证明你的住址。两个人嗓门很大，争执了很长一段时间，老哥说这次第五次来开户了，每次让我准备这个准备那个，结果这次带了信封还是不行。最后灰溜溜地离开了。
12点56分轮到了我，刚坐下来就问我开户需求，我说投资理财，她说投资什么，我说可能就港股，她让我给她看A股的投资经验，我说我没玩过股票，大学刚毕业。她要我提供工作证明，我给她看了之前的工作邮箱截图，她说这上面没有公司名，我说邮箱后缀还不能说明公司嘛。最后看这看那看了一通之后，她还是表现地不给开。她说没有投资经验你就玩港股我可以有权利不给你开户。我问她初学者不能直接入门港股？最后她一定要我提供资产证明。我让她出示开户相关条件的文件。最后在我的一再回怼下，我跟她说这些所谓的你需要的材料你也不需要上传系统，也不需要复印，也不需要留档。为什么一定要咬着不放呢？她说开户之后必须要保证账户里面有10000港币，我问她不到怎么办，她说会影响功能。我问她什么功能，她回答不上，就说会影响功能。我问她有没有账户管理费之类的，她说没有。
最后就是开户的流程了，就是给她看身份证、港澳通行证、入境小票。接着就是设置密码，两个食指按指纹。大概10多分钟就搞定了。开户实际用时非常短，主要是前面那些问题非常恶心。我完成所有手续大概是下午的1点34分。
我是上水中心分行周六的最后一个客户，也就是意味着到下午1点最多只能完成20个号，实际上只完成了不到10个号，因为很多客户等不及就走掉了，就跳过了。所以这个效率真的很感人。我预计如果是周一到周五的话，也最多完成40-50个号。
开户材料准备 中国大陆身份证原件 港澳通行证 入境小票 地址证明文件（可选）：关于地址证明是如果你收实体卡片的地址不是你身份证上的地址，那么就必须要提供地址证明文件，常见的可以是大陆信用卡的账单，正常的大陆银行每个月会给你预留的邮箱发送一份PDF文件，如果没有可以向银行索要。你可以准备近三个月的信用卡账单，但是不能是PDF版本的，必须得是打印好的实体件。你可以留意一下是否包含你的名字和你的地址，一般情况下都是有的。 手机号码：我用的是香港手机号，大陆手机号应该也可以，但是必须要在入境香港前向您的运营商开通漫游服务，否则你的手机卡会一直显示无服务的状态，无法收发短信。 BOCHK App：强烈建议提前在手机上下载好BOCHK App。 一些建议 分行选择 不要选择中港城分行这些。在尖沙咀附近那块的分行应该人不会少。可以选择上水中心分行、粉岭中心分行、荃湾分行、屯门市广场分行这些相对来说比较冷门一点的地方。当然如果你有兴趣的话，我倒是希望你可以去一下广东道分行，这个号称只接待高端用户的中银理财中心能不能开户成功。
时间段选择 不要选择周六，除非你愿意9点前就赶到门口排队。周一到周五也尽量选择10点前到达。
实体卡邮寄 柜员说是30天之内到，据说是平邮，查不到邮寄信息，只能多去信箱看看了。

**Comment by missuo** [comment]
测试评论

**Comment by Bonny07** [comment]
非常有帮助😆
