### ISSUE TITLE
About | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#22]
https://missuo.me/about/ 

 Welcome to my website, I am very happy to meet you!
🏠 About this site This site is mainly used for the personal life of the blogger.
👨‍💻 Who is the blogger Vincent(YingTao) Young Libra, born on October 10, 2000 From Zhejiang, usually living in Shanghai College student, studying Computer Science ⛹ Interests Basketball (Golden State Warriors fans) Travel (love to go see the sea) Programming (working on learning Flutter) 📬 Contact me Email: i@yyt.

**Comment by Fi-tz** [comment]
dude ive been using your injected wechat for a while ,and i wanna ask this question,if you still devote to do such a work ,cause i need that file,seriously

**Comment by missuo** [comment]
> @Fi-tz
> dude ive been using your injected wechat for a while ,and i wanna ask this question,if you still devote to do such a work ,cause i need that file,seriously

follow this link: https://repo.owo.network
