### ISSUE TITLE
Summary of University Life | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#24]
https://missuo.me/posts/university-life/ 

 时间过得真的很快，从小学毕业到现在快十年了，还有三个月我就要本科毕业了。最近的生活没什么压力，可以让我静下来思考很多东西。
小学的时候第一次接触电脑，在当时看来如此神奇的东西。那时候最新的操作系统还只是 Windows XP，而有些人还在用着古老的 Windows 2000/98。那时候是我第一次接触键盘，开始练习打字，实在记不起来当时的那款打字游戏叫什么，只记得只有不断的打字才能逃跑，后面有警察一直在追着你，如果被抓到了就输了。是啊，在现在看来可能有些幼稚，那时候打字比赛获得了一等奖。不过那时候没有什么机会好好玩电脑，最多用的软件可能就是 QQ 吧。直到我小学六年级毕业那个暑假，我有了很多的时间可以去琢磨，我第一次接触的编程语言是易语言，那时候流行用易语言来做钓鱼程序盗号，我也有玩过。
再后来去了初中，那是 2013 年，我开始接触 Scratch 和 VB，也是在那时认识了那个让我爱上编程的老师，幸运的是现在我还和他有保持联系。除了玩 Scratch 做一些小游戏，VB 写一些简单的程序之外，我在初三的时候开始接触服务器、域名和博客。那时候用的叫 Hostker 的虚拟主机，现在好像还活着。我买了一个域名，用一个 HTML 单文件搭建了我的第一个博客。后来也买了一个我初中全拼的域名，搭建了 Disquz 校园论坛。
再后来就是高中，但是老实说我的高中几乎没有接触电脑，都是在玩手机。那个时候王者荣耀很火，微信也慢慢开始不仅仅是支付工具。高中也有技术课，甚至高考也会考相关的知识，但是那个时候提不起什么兴趣，老师上课也只是让你记住知识点，也不会给你解释为什么。所以相对来说，有些枯燥乏味。
直到大学，我记得那是 2019 年 8 月，我收到了我的第一台 Macbook Pro，开始了我的编程生涯。从 C 语言开始，再到 Java。但是老实说除了在上那两门课之后，我再也没写过 C 和 Java。感觉 C 语言我一般不太用的到，只有在写 Arduino 的写过一些 C++。至于 Java，我似乎没有机会写，坚决不用 Java 写 Backend，我只是觉得明明有更好的选择，不想变得复杂化。我自学了 Python，JS，Shell，PHP，Golang。我会用 Python 写一些简单的爬虫，又或者是数据的处理，它真的太方便了。我也在 PyPi 贡献了一些我写的 Package。至于 JS，有时候在写 H5 的时候会偶尔用到，我也用 JS 写过项目的 Backend，称不上喜欢，但也不讨厌，自己很少用，因为我讨厌在服务器上部署 Node 环境。Shell 是我最常用的之一，我用它写了不少好用的脚本，实现了一些自动化或者是一键安装。PHP 我会用它写一些简单的 PHP，毕竟只要把它丢到网站根目录就好啦，太方便了。Golang 是我最晚接触的，大概也就是在半年前，我现在主要用它来写 Web API，Gin 和 Grom 太方便了。
好好回忆起大学的这四年，我好像几乎都在学一些我自己喜欢的东西，和 Leo 一起玩 VPS，一起探索世界互联网五花八门的路由，一起在 GitHub 做开源贡献。这确实很快乐。我们可以一起在图书馆或者工作室玩一整天关于 XrayR、Nginx、CDN，还有好多奇怪的玩法。我们也会测试学校的一些系统的 API 是否可以 SQL 注入。也许在这些时间里，让我更加热爱计算机。

**Comment by superpung** [comment]
Hello Vincent，很喜欢你的 blog，给了我很多帮助。祝顺利！

**Comment by thedavidweng** [comment]
你是否在寻找：[《金山打字通》- 生死时速](https://www.bilibili.com/video/BV1Eb411c72M/)
