### ISSUE TITLE
2019 Hong Kong Travel | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#27]
https://missuo.me/posts/2019-hong-kong-travel/ 

 Transportation Train T211(Jiaxing Railway Station - Shenzhen Railway Station) Bus B3X(Shenzhen Bay Port - Tuen Mun Town Centre) Accommodation USA Hostel Mirador Mansion, 54-56B Nathan Rd, Tsim Sha Tsui, Hong Kong
Photos

**Comment by 1137882300** [comment]
请问 图床 您用的是什么呀？想参考一下

**Comment by missuo** [comment]
> @1137882300
> 请问 图床 您用的是什么呀？想参考一下 

Cloudflare R2
