### ISSUE TITLE
SIM card I am using | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#36]
https://missuo.me/posts/sim-card/ 

 境外 中国移动香港 CMHK 资费：2HKD/mo
保号：每充值 50HKD 续费 180 天
用途：绑定 BOCHK 账户，注册 WeChat 等
上车价格：30CNY（几年前的价格，现在涨价了）
Giffgaff 资费：0GBP/mo
保号：每半年发送一次短信或者拨打一次电话
用途：注册 OpenAI，绑定 WeChat 等
上车价格：30CNY/2 张
Globe 资费：0PHP 保号：半年充值 5CNY 用途：注册 Paymaya，注册 Gcash 等 上车价格：11CNY
PayGo 资费：3USD/mo 保号：每月正常扣款 3USD，没有别的要求 用途：绑定美区 PayPal 等 上车价格：13USD eBay
境内 中国移动 China Mobile 套餐：8 元飞享套餐
资费：8CNY/mo
用途：这是我最老的号码，绑定了不少服务，现在使用 无忧行 App 仅收短信
中国联通 China Unicom 套餐：浙江沃派 5G 套餐（44G + 300 分钟） 资费：28CNY/mo 用途：主用上网通话卡
中国联通 China Unicom 套餐：大王卡（70G） 资费：29CNY/mo
用途：备用上网卡

**Comment by Bonny07** [comment]
同款paygo ultra mobile电话卡，好用

**Comment by mrmyn** [comment]
> @Bonny07
> 同款paygo ultra mobile电话卡，好用

请问也是在楼主推荐的ebay购买的吗，如果在国内，直接在ebay购买可行吗？

**Comment by missuo** [comment]
> @mrmyn
> > @Bonny07
> > 同款paygo ultra mobile电话卡，好用
> 
> 请问也是在楼主推荐的ebay购买的吗，如果在国内，直接在ebay购买可行吗？

不可行。如果你有 eSIM 的手机我可以帮你买，如果没有的话，你只能自己想想办法了，

**Comment by mrmyn** [comment]
> @missuo
> > @mrmyn
> > > @Bonny07
> > > 同款paygo ultra mobile电话卡，好用
> > 
> > 请问也是在楼主推荐的ebay购买的吗，如果在国内，直接在ebay购买可行吗？
> 
> 不可行。如果你有 eSIM 的手机我可以帮你买，如果没有的话，你只能自己想想办法了，

谢谢，我还是关注国内一些实体卡渠道，请问这种ultra mobile是否不如t-mobile(在国内一直用下去...不会被ban,想把外网账号比如Google之类的绑定)稳定呢?
