### ISSUE TITLE
HSBC Hong Kong One Account Opening Guide | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#43]
https://missuo.me/posts/hsbc-hk-one-account/ 

 相比 BOCHK，HSBC HK 的服务好太多了！而且 HSBC 开户更加容易。网点也比较多，工作人员也非常友好，不会刻意刁难。最关键的是 HSBC 可以申请一张 Debit Card，可以绑定 Apple Pay 消费，非常方便。
准备材料 港澳通行证 大陆身份证 入境小票 BOCHK 如果你的通讯地址不是身份证的地址，必须要提供地址证明文件，例如信件、水电费或信用卡账单等等。如果通讯地址和身份证一致，则无需提供。而 HSBC 向你询问通讯地址的时候，不需要提供任何证明文件，仅需在纸上写下全英文地址即可。
开户过程 网点选择 尽量去一些人比较少的网点，我有幸去过三家网点，第一家在香港岛的 電氣道分行，这家是我开户的网点，工作日上午 11 点左右过去，等待时间不长，相比 BOCHK 3 个多小时来说，这家就等待了 10 多分钟。第二家是在中环的 香港总行，虽然办理窗口很多，但是等待的时间相当久，大概有一个多小时。第三家是在会展和湾仔附近的 新鸿基中心分行，等待时间不是很久。
开户前的咨询 一般情况下，上来先会问你开户的需求，请不要说用来购物消费之类的理由，她会拒绝你的开户请求，因为大陆的信用卡或者 Alipay 之类的在香港都可以用，工作人员认为你完全没必要开户 HSBC。一般的说辞是 投资理财买保险，你就说“听说香港这边的存款利率会比较高，我想把钱存在你们银行”，工作人员会问你大概会存多少钱，你就回答 10 万港币以上。另外还会问你第一笔存款大概会在多少，你就回答几万港币。请记住一定不要说几千，否则可能会被拒绝。
开户过程 大概就是录入你的一些信息，其实倒也不会很慢，需要签几次名字。开户成功之后，会给你一个信封，里面有一张卡，叫作 提款卡。提款卡，顾名思义只能取款或者存款。信封里面还会有这张卡的初始密码，建议找一台 HSBC ATM 修改成你常用的。开户完成之后可以在 HSBC App 上申请 Debit Card，会寄到你的通讯地址，默认是平邮，不能指定。大概 2-3 周如果还没有收到信件的话，可以打电话要求补寄，补寄可以要求挂号信或者 DHL 快递，DHL 需要自己清关。
关于 One 和 Premier 账户 HSBC 在中国大陆是没有 One 账户的，中国大陆开户的最低等级是 Premier，开户条件是有 50 万人民币以上的存款、理财或保险。而且必须要始终保持 50 万人民币，否则将收取高额的账户管理费。

**Comment by mrmyn** [comment]
HSBC 推荐直接去新加坡开卡吗，有家人在那边工作
