### ISSUE TITLE
I closed my CCB account. | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#44]
https://missuo.me/posts/close-ccb-account/ 

 从来没有一家银行让我如此气愤，但是 CCB 值得我写一篇博客来发泄一下。
其实我自己从来没有主动办理过 CCB 借记卡。在 2019 年开学的时候，学校应该是和 CCB 有合作，统一帮忙开通了一张 CCB 的借记卡，还是学校定制的卡面，主要用于每个学期退还代办费。但是拿到的空卡是没法直接使用的，需要带上身份证件排队激活，当时由于新生太多了，排队需要很长的时间，我就计划着到时候自己去网点激活就好，暂时也不急着使用。
后来有一次假期刚好回家了，在浙江省嘉兴市，我去了 CCB 嘉兴分行取了一个号，准备激活我的借记卡，没想到第一次在 CCB 的体验就让我破防了，我取了号码之后，有源源不断的人插队，而且他们根本就不需要取号就可以直接上柜台办理业务。那一次是我第一次投诉银行，我记录了现场工作人员的所有工号和名字，包括大堂经理和柜台允许插队的柜员。但是后来的投诉似乎也没有很明显的效果，只是电话回访跟我道歉。
第二次去 CCB 网点是在上海，那一次的记忆有些模糊了，大概就是 CCB 说的卡片的个人信息需要补充，好像是职业信息当初没有填写，所以卡片暂时被冻结了，必须要前往网点补充信息，虽然说真的很麻烦，但是这也没办法，只能妥协。那一次等待了大概 30-60 分钟，还算是能接受。
第三次去 CCB 网点又是在浙江省嘉兴市，由于过去的三年我换过几次手机，然后 CCB 的手机 App 换设备，必须要在老设备上解绑，或者插入绑定的手机卡开着蜂窝数据才可以验证，再不行只能去网点解绑设备。这一点是最让我气愤的，因为一直登录不了手机客户端，我就一直不登录。那天刚好路过 CCB 嘉兴分行，我就进去寻思着换个绑定的手机号，或者就让他们帮我解绑一下老设备。没想到的是，我只带了身份证，自助机器和人工柜台都无法办理这个业务，必须要卡片，工作人员声称必须要有介质，否则系统无法操作。我要求挂失补卡办理这个业务，工作人员说挂失补卡必须要换卡号。我又要求不换卡号换卡，工作人员又说不换卡号换卡必须要提供原卡片。简单说，就是要办理手机银行解绑老设备还得再来一次。
第四次去 CCB 网点还是在浙江省嘉兴市，这次去的是另外一家支行，这次我带上了卡片和身份证，顺利地解绑了老设备，在新的手机上成功地登录了 CCB 客户端。但是因为这张卡片有限额，我要求把限额调高一些，否则很多时候卡里有钱，但是无法转出或者消费。工作人员要求我出示社保卡，但是我没有携带社保卡，但是支付宝上可以看到电子社保，工作人员认定不能作为提额的材料，我说我有本人房产证和存款证明电子版，让他们帮忙打印一下，他们认为电子版的材料一样不能作为提额材料。我又说我往这张卡片里面存入一定数额的存款，让他们本行开具存款证明，将该存款证明作为提额材料，工作人员依然告诉我不行。
第五次去 CCB 网点是因为我毕业了，不再需要这张卡片，也不想再和 CCB 有任何的联系，CCB 足够让我失望，我决定销户。我又到了一家从未去过的网点，跟大堂经理说，我要销户。她给我取了一个 现金业务 的号，但是我看到现金业务有很多人在排队，我说我卡里没有任何余额，不能在非现金业务窗口办理嘛。她让我去尝试一下，结果非现金业务的系统在执行销户操作的时候，需要选择一个承接账户，意思是剩余的余额要有一个别的建行账户接收，但是我没有别的建行账户，无法进行下一步。但是很离谱的是，我明明没有余额，但是系统仍然强制要求选择一个承接账户，否则下一步是灰色的。 后来我等了 45 分钟上柜台完成了销户，我立即删除了 App，心里还是有些开心了，终于不用和这家银行有任何的接触了。
总结 CCB 的网点办理业务的系统设计的非常烂，比如解绑手机银行设备，必须要卡片作为介质，非常死板。比如在非现金业务销户的时候，明明卡片没有任何余额，必须要选择承接账户显然不合理。 CCB 的手机 App 设计的非常古老，在人脸识别还没有普及的时代，它这样的设计是为了安全，但是在 2023 年这个时间，大部分的银行 App 在登录新的设备时，仅需要绑定的手机接收验证码，再加上人脸识别即可，但是 CCB 没有人脸识别的选项。 CCB 对于工作人员的管理非常随意，允许不取号插队的行为，大堂经理经常消失在大堂，导致大堂空无一人，更离谱的是在还有 10-20 人等待办理业务的时候，仅开放一个柜台办理业务，这个情况在我去的每个支行和分行同时存在。 CCB 工作人员的素质普遍不高，某支行的工作人员以阴阳怪气的态度和客户交流，分行的所谓的“领导”在工作时间不穿工作服装，并且不愿意出示任何工牌。当我有一次和所谓的“领导”交流的时候，某工作人员直接报警了。我们在交流中并没有出现任何不文明的言语，也没有任何的肢体接触，工作人员却选择了报警解决问题。 CCB 的投诉热线形容虚设，由于为了方便 CCB 的领导处理我的投诉问题，我在每次投诉的时候都上报了办理业务的工作人员的工号和名字，但是似乎最终等到的回复就是只有道歉，却没有任何实质性的改变。而且我要求进一步核实的时候，投诉回访的工作人员表示同意，但是在挂断电话后立即标记投诉工单的状态为已完成。 以上是我了解的我所在城市的 CCB，别的城市是不是也是一样，我不得而知。

**Comment by Bonny07** [comment]
解绑设备真的是让人头大，之前我手机出问题不能用，当时又被迫在家不能出门。这个时候我想用备用机绑定银行卡，结果是完全不能动。

**Comment by liunian-zy** [comment]
重置手机银行密码也是，我卡找不到了，拿身份证也不行，真离谱啊
