### ISSUE TITLE
iOS App Self-Signing and Multi-Opening | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#50]
https://missuo.me/posts/sign-ios-app/ 

 最近好像很多人对这个很感兴趣，我就简单介绍一下。
自签名有什么用 iOS 本身不支持多开，比如微信你只能同时登录一个，不像安卓。所以非常的不方便，自签名就可以实现双开，甚至是多开。
iOS 的 App 正常情况下只能通过 App Store 下载，有些好用的 App 价格又非常贵，而自签名可以直接安装破解版 App。比如 X(Twitter)、Instagram 这些去广告，微信防撤回等等。我就不一一列举了，能实现的功能非常多且强大。
简单说，就是多开和破解。
准备工作 签名的时候需要开发者证书，证书主要分为两大类，企业证书和个人证书，但是企业证书一般很难搞到，所以本文介绍的是个人证书。
获取个人证书之前，你需要知道你设备的 UDID，开发者需要将你的设备添加到测试设备中。每个开发者一共可以添加 100 台设备。你可以自行某宝或者找别的路子购买，售价大概在40-100不等一年。
购买证书需要提供 UDID，这个编号不会因为你刷机重装系统而改变。获取的方式，可以点 这个链接，需要安装一个描述文件。获取那一串字符串之后，记得保存一下。然后就可以删除这个工具的主屏幕图标和描述文件，之后不再需要用到。
证书 证书包含一下两个文件：
xxxx.p12 xxxx.mobileprovision 一般的证书签发的时间为一年。你买到的证书一般是不满一年的，因为不是实时生成的，这是很正常的。建议从靠谱的来源购买证书，因为如果一年之后到期，如果用同一个开发者的证书，可以直接覆盖安装，会保留 App 的数据，比如微信的聊天记录。如果使用不同开发者的证书无法覆盖安装，可能会丢失 App 数据。
签名 主流的签名工具，主要有 全能签 和 轻松签(Esign)，前者功能几乎一样，我个人一直用的 全能签。
当然啦，这是手机上的签名工具，你也可以用电脑签名，例如 iOS App Signer，功能没有手机端强大，例如移除应用跳转这些需要自己改动 .ipa 包。
安装全能签 请选择 “我有证书|自助安装”，上传 p12 和 mobileprovision 文件，输入 p12 证书的密码。
安装完之后可能会提示无法打开，会引导你到设置里面开启 开发者模式。如果你没有安装全能签，一般情况下从 iOS 16 开始你是看不到 开发者模式 这个选项的。开发者模式在 设置 - 隐私与安全性，划到最底下，你可以看到 锁定模式 和 开发者模式。开启开发者模式之后会重启手机，重启之后点击确认开启即可。

**Comment by luoyhang003** [comment]
注册Apple个人开发者的话可以搞定p12和mobileprovision吗

**Comment by missuo** [comment]
> @luoyhang003
> 注册Apple个人开发者的话可以搞定p12和mobileprovision吗

是的。

**Comment by luoyhang003** [comment]
> @missuo
> > @luoyhang003
> > 注册Apple个人开发者的话可以搞定p12和mobileprovision吗
> 
> 是的。

想再请问一下，安装全能签需要的Apple个人开发者的p12证书类型和mobileprovision类型是什么呢？我安装全能签一直提示【无法安装 全能签】

**Comment by missuo** [comment]
> @luoyhang003
> > @missuo
> > > @luoyhang003
> > > 注册Apple个人开发者的话可以搞定p12和mobileprovision吗
> > 
> > 是的。
> 
> 想再请问一下，安装全能签需要的Apple个人开发者的p12证书类型和mobileprovision类型是什么呢？我安装全能签一直提示【无法安装 全能签】

说明你设备的 UDID 没有被添加到测试设备列表中。

**Comment by thedavidweng** [comment]
捉虫，https://t.me/missuo_ipa 你在文中写成 https://t.me/missuo-ipa 了

**Comment by missuo** [comment]
> @thedavidweng
> 捉虫，https://t.me/missuo_ipa 你在文中写成 https://t.me/missuo-ipa 了

感谢

**Comment by robustmaster** [comment]
学会了，感谢。
