### ISSUE TITLE
Decided to study in the United States | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#51]
https://missuo.me/posts/study-in-the-us/ 

 截止到写这篇文章，已经在美国接近两个月左右的时间了。其实早就该写这篇文章了，一直没想好怎么写，就拖到了现在。
契机 我本科读的专业是 CS 4+1 的项目，也就是说四年本科读完之后，可以去美国继续读一年，就可以获得硕士的学位。因为是合作的项目，学费和录取条件都比较低，除此之外时间也非常短，因为有几门美国学校的课程可以充当本科的学分，也可以充当研究生课程的学分。但是其实从大一开始也没有很强烈的想法去美国参加这个 4+1 的项目，主要的原因就是觉得合作的学校排名太一般了。
直到 20 年的差不多寒假后，那时候疫情刚刚爆发。有一款很火的软件上线，叫作 Clubhouse，当然这款软件也是昙花一现，现在几乎是没有人使用了。这是一款语音聊天室的软件，任何人可以选择进入感兴趣的聊天室，可以倾听别人发言，当然也可以申请上麦发言，当时我在家上网课的阶段，每天就是玩这个软件。那时候这个软件上有很大一部分人都在北美，或者英国，当然国内的也有。有好几个在美国做程序员的前辈，咨询了一下在美国找程序员工作前景如何，他们当时的说法是 Amazon 基本上是所有应届生都先会去的地方，然后干两三年之后跳巢，因为 Amazon 很好进，招的人特别多。
那个时候就已经有点想去美国读 Master 的想法，但是也还没有任何行动。后来，国内的疫情越来越严重，连着就是好几年，我人生中的第一份工作都是远程入职、远程办公和远程离职的，因为疫情的原因，我甚至没有去过公司，我不知道公司的办公环境是怎么样的，我也没有领取到实体的工卡，本来还想着离职前可以拍照做个纪念。21 年的时候就开始有很多互联网公司裁员，找工作难的新闻。也就是那个时候，我开始决定去美国，当时看来美国的就业环境比国内还是好很多的。于是那年的国庆过后，和爸妈商量之后，我找了留学中介，报了语言培训班。
申请前的准备 我记得应该是 11 月，我开始学习 TOEFL。因为家在浙江，但是学校在上海。培训的机构我又选择了在杭州，那个时候就是每周末上海-杭州来回奔波。周末几乎是没有休息的时间，好在是大三了，课程不是很多。暑假我又开始连着上课，一个星期只有一天的休息时间。差不多在 23 年 4 月份左右，我准备好了 TOEFL 和 GRE，接下来就是一些文书、成绩单和推荐信的准备。美国留学申请是最繁琐的，需要的材料非常多。虽然说找了中介，但是中介也就是解答我的一些疑问，以及帮忙规划申请的学校和提供文书，剩下的都是我自己操作的，包括上传资料，填写信息，递交申请等等。不过好在这一套流程下来，我也熟悉美国研究生申请。
在找中介的之后，其实我就没有多想，没有考虑美国以外的国家。原因主要是我当时的决定就是想读完研究生留在当地的国家工作，至少是工作几年，积累一些海外的工作经验，刚好也锻炼一下自己口语能力。所以，英国和澳洲就基本排除了，英国几乎拿不到工签，澳洲需要 2 年以上的项目才有可能拿工签，而计算机研究生的项目基本上都在 1.5 年左右。我好像没什么别的选择，唯一的选择就是美国，美国最坏的打算就是抽不到 H1B，也至少可以用 CPT 实习和 OPT 的三年全职工作。
开始申请 我差不多从 22 年 11 月开始陆续递交申请，直到 23 年的 2 月份左右递交了所有的申请，一共是 11 个项目。最终收到 Offer 的一共是 4 个项目。在写这篇文章的时候，回想起来还是有些后悔，比如像 CMU 我当时压根就没有申请。 看到大佬 halfrost 的这篇文章的时候，其实我的申请已经结束了，很多学校的申请截止日也已经过了。我当时申请的时候，说实话有些头铁，我只申请 CS 专业，任何别的例如 CE、EE 之类的专业我一律不申请。导致我最后收到的 Offer 也不是很多，如果再让我重来一次的话，我可能会选择申请 CMU 的冷门一些的专业，或许会有希望，就当是买个彩票吧。

**Comment by thedavidweng** [comment]
你有领英吗

**Comment by missuo** [comment]
> @thedavidweng
> 你有领英吗

有啊

**Comment by thedavidweng** [comment]
> > @thedavidweng
> > 你有领英吗
> 
> 有啊

来 Connect
