### ISSUE TITLE
2023 year-end summary | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#60]
https://missuo.me/posts/summary-2023/ 

 最近比较繁忙，还没有好好整理过去的一年发生的事情。当然，过去的这一整年是我人生中最重要的一年。打算把这篇文章留到夏威夷飞东京的航班上，那时候没有网络，我会在抵达东京之后推送。

**Comment by xiln7** [comment]
请问那班航班还有多久起飞呢？期待博主的年终总结

**Comment by missuo** [comment]
> @xiln7
> 请问那班航班还有多久起飞呢？期待博主的年终总结

会在合适的时候更新。2023年还有几天。
