### ISSUE TITLE
Chat With Strangers | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#63]
https://missuo.me/posts/chat-with-strangers/ 

 之前有看到 GeekPlux 一直有在和陌生人聊天。我最近也比较无聊，所以也搞了一个预约聊天的页面。欢迎大家来和我聊天。
聊天内容 留学 润学 工作 其他任何话题 聊天方式 仅支持语音的方式，推荐使用 Google Meet，我们可以聊任何话题。如果您所处的网络无法使用 Google Meet，可以改用别的语音聊天工具，当然聊天的内容会受限。
如何预约 您可以点击 这个链接 预约任何空闲的时间，预约成功之后请给我 发邮件 告诉我您想聊得大概内容。如果临时有事情需要改时间请通过邮件联系我。

**Comment by thedavidweng** [comment]
第一次知道 Cal 这个平台，Free Tier 的权益比 Calendly 慷慨，试试。
