### ISSUE TITLE
CIB Wire Transfer Fee | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#72]
https://missuo.me/posts/cib-wire-transfer/ 

 全网最全的兴业银行 (CIB) 寰宇人生/无界卡电汇手续费汇总。仅适用于寰宇人生/无界卡用户。
寰宇人生和无界卡是手续费和电报费全免，但是中转行（如果有）和收款行可能会收取手续费。
我在 CIB 官网找到了一份名单，以下是 CIB 在境外所有的账户行。如果你从兴业银行中国大陆汇款到这些账户行，且汇款的币种都是名单中的币种，那么不会产生中转行，唯一有可能产生的费用就是收款行的费用，这一点无法避免。
账户行名单
已知的全程无损收款的账户行（即不存在收款行手续费）：
HBSC US (USD) HBSC UK (HKD) 欢迎补充！！！
如果您刚好在使用 CIB 寰宇人生/无界卡，有时间的话请在每次汇款之后填写以下表单，供其他网友做参考。
电汇手续费填报表
以下是由热心网友贡献的信息：
CIB 汇款 DP

**Comment by thedavidweng** [comment]
写过 CIB 寰宇人生/无界卡的介绍吗

**Comment by thedavidweng** [comment]
你的评论是 Issue 还要手动关也太搞笑了
