### ISSUE TITLE
My third ASN and IP resource request | Vincent's Notes

### ISSUE THREAD

**Issue by missuo** [missuo/missuo.github.io#80]
https://missuo.me/posts/my-third-asn/ 

 最近我申请到了我的第三个 ASN，并且成功获取到了一些 IPv4 和 IPv6 资源。
专有名词 在介绍这些之前，有必要科普一下一些专有名词。
ASN: Autonomous System Number，自治系统号，用于标识一个自治系统。 IP: Internet Protocol，互联网协议，包括 IPv4 和 IPv6。 RIR: Regional Internet Registry，区域互联网注册管理机构，负责分配 IP 资源。 ARIN: American Registry for Internet Numbers，美国互联网数字注册管理机构。 APNIC: Asia Pacific Network Information Centre，亚太网络信息中心。 RIPE: Réseaux IP Européens Network Coordination Centre，欧洲网络协调中心。 在全世界一共有 5 个 RIR，分别是：
ARIN: 美国 RIPE: 欧洲 APNIC: 亚太 （其中 APNIC 下还有 NIR，例如 CNNIC，TWNIC 等等） LACNIC: 拉丁美洲 AFRINIC: 非洲 我的第一个 ASN { "asn": 206729, "name": "VINCENT-NET-AS", "description_short": "Vincent Yang", "description_full": [ "Vincent Yang" ], "country_code": "CN", "website": "https://vincent.

**Comment by Chenming00** [comment]
等一个公司教程
